# Generated by Django 5.0 on 2023-12-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarea_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mimodelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo1', models.CharField(max_length=50)),
                ('campo2', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='tarea',
            name='completada',
            field=models.BooleanField(default=False),
        ),
    ]
